# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mouyIaxu2QdCV7xTr1WGiMW3YFkf7lfJ
"""

Number = 31

if Number%2 == 0:
  print('Given number is Even')
else:
    print('Given number is Odd')